### ISSUE TITLE
Broken re-indexing when flat tables are switched off

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#18]
Hi,

In my System->Config->Catalog I have flat category and flat product tables switched off. 

When running bin/magento index:reindex, the BV plugin seems to assume that I am using flat tables thus breaking the indexing process:

```
#0 /home/ccarnell/Sites/vax-uk2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /home/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `p`.`nam...', Array)
#4 /home/ccarnell/Sites/vax-uk2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `p`.`nam...', Array)
#5 /home/ccarnell/Sites/vax-uk2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `p`.`nam...', Array)
#6 /home/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Select.php(711): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select))
#7 /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(463): Zend_Db_Select->query()
#8 /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(218): Bazaarvoice\Connector\Model\Indexer\Flat->reindexProductsForStore(Array, Object(Magento\Store\Model\Store\Interceptor))
#9 /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(183): Bazaarvoice\Connector\Model\Indexer\Flat->reindexProducts(Array)
#10 /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(141): Bazaarvoice\Connector\Model\Indexer\Flat->execute(Array)
#11 /home/ccarnell/Sites/vax-uk2/vendor/magento/module-indexer/Model/Indexer.php(412): Bazaarvoice\Connector\Model\Indexer\Flat->executeFull()
#12 /home/ccarnell/Sites/vax-uk2/generated/code/Magento/Indexer/Model/Indexer/Interceptor.php(323): Magento\Indexer\Model\Indexer->reindexAll()
#13 /home/ccarnell/Sites/vax-uk2/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer\Interceptor->reindexAll()
#14 /home/ccarnell/Sites/vax-uk2/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(86): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#15 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Command/Command.php(242): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Application.php(845): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Application.php(196): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/ccarnell/Sites/vax-uk2/vendor/magento/framework/Console/Cli.php(104): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Application.php(117): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/ccarnell/Sites/vax-uk2/bin/magento(23): Symfony\Component\Console\Application->run()
#21 {main}
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2_prod.catalog_category_flat_store_18' doesn't exist, query was: SELECT `p`.`name`, `p`.`type_id` AS `product_type`, `p`.`entity_id` AS `product_id`, `p`.`short_description` AS `description`, `p`.`sku` AS `external_id`, `p`.`small_image` AS `image_url`, `p`.`visibility`, `p`.`bv_feed_exclude`, GROUP_CONCAT(DISTINCT parent.sku SEPARATOR "|") AS `family`, `parent`.`small_image` AS `parent_image`, `url`.`request_path` AS `product_page_url`, `parent_url`.`request_path` AS `parent_url`, max(cat.entity_id) AS `category_external_id`, max(parent_cat.entity_id) AS `parent_category_external_id`, `p`.`name` AS `en_GB|name`, `p`.`short_description` AS `en_GB|description`, `p`.`small_image` AS `en_GB|image_url`, `url`.`request_path` AS `en_GB|product_page_url`, `parent_url`.`request_path` AS `en_GB|parent_url`, `parent`.`small_image` AS `en_GB|parent_image`, MAX(cl.version_id) AS `version_id` FROM `catalog_product_flat_18` AS `p`
 LEFT JOIN `catalog_product_super_link` AS `pp` ON pp.product_id = p.entity_id
 LEFT JOIN `catalog_product_flat_18` AS `parent` ON pp.parent_id = parent.entity_id
 LEFT JOIN `catalog_category_product_index` AS `cp` ON cp.product_id = p.entity_id AND cp.store_id = 18
 LEFT JOIN `catalog_category_product_index` AS `cpp` ON cpp.product_id = parent.entity_id AND cpp.store_id = 18
 LEFT JOIN `url_rewrite` AS `url` ON url.entity_type = 'product'
                AND url.metadata IS NULL
                AND url.entity_id = p.entity_id
                AND url.store_id = 18
 LEFT JOIN `url_rewrite` AS `parent_url` ON parent_url.entity_type = 'product'
                AND parent_url.metadata IS NULL
                AND parent_url.entity_id = parent.entity_id
                AND parent_url.store_id = 18
 LEFT JOIN `catalog_category_flat_store_18` AS `cat` ON cat.entity_id = cp.category_id AND cat.level > 1
 LEFT JOIN `catalog_category_flat_store_18` AS `parent_cat` ON parent_cat.entity_id = cpp.category_id AND parent_cat.level > 1
 LEFT JOIN `bazaarvoice_product_cl` AS `cl` ON cl.entity_id = p.entity_id WHERE (p.entity_id IN('806', '807', '808', '809', '810', '811', '812', '813', '814', '815', '816', '817', '818', '819', '820', '821', '822', '823', '824', '825', '826', '827', '828', '829', '830', '831', '832', '833', '834', '835', '836', '837', '838', '839', '840', '841', '842', '843', '844', '845', '846', '847', '848', '849', '850', '851', '852', '853', '854', '855')) GROUP BY `p`.`entity_id`
```

**Comment by chrismshea** [comment]
Flat tables are a requirement of the extension.  Though the indexing process should not fail if they are not yet enabled.  We'll put in a fix for that.  Flat tables will need to be enabled for the Product Feed to function.

**Comment by craigcarnell** [comment]
@chrismshea Thanks. In a production ready release they will be enabled in the future. But a fix now would be great :+1:

**Comment by chrismshea** [comment]
This fix will be included in 7.1.0, but here's a link to the source where it has been resolved.
[Flat.php](https://github.com/bazaarvoice/magento2-extension/blob/release-710/Model/Indexer/Flat.php)

**Comment by craigcarnell** [comment]
@chrismshea Hi Chris, when is the next release?

**Comment by chrismshea** [comment]
Should be out this week.
