### ISSUE TITLE
fatal error during magento setup:di:compile

### ISSUE THREAD

**Issue by mutantturkey** [bazaarvoice/magento2-extension#22]
See below traceback when I run setup:di:compile on a fresh 2.2 enterprise installation.
```

calvin@dev1:~/src/magento-simple-site$ bin/magento  setup:di:compile
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/calvin/src/magento-simple-site/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php:104
Stack trace:
#0 /home/calvin/src/magento-simple-site/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Bazaarvoice\Connector\Model\Indexer\Flat->__construct(Object(Bazaarvoice\Connector\Logger\Logger), Object(Bazaarvoice\Connector\Helper\Data), Object(Magento\Indexer\Model\Indexer\DependencyDecorator), Object(Magento\Framework\App\ObjectManager), Object(Magento\Store\Model\StoreManager\Interceptor), Object(Bazaarvoice\Connector\Model\ResourceModel\Index\Collection\Factory), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Framework\App\Config))
#1 /home/calvin/src/magento-simple-site/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Bazaarvoice\\Con...', Array)
#2 /home/calvin/src/magento-simple-site/vendor/mage in /home/calvin/src/magento-simple-site/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php on line 104
calvin@dev1:~/src/magento-simple-site$ 

```

**Comment by chrismshea** [comment]
Hi Calvin,

This would happen if there is no default store set on the website.  I tested on a fresh install of 2.2 without sample data installing version 7.1.1, and did not receive any errors during compilation.
