### ISSUE TITLE
Extension breaks product page when enabled on Magento 2.2.2

### ISSUE THREAD

**Issue by careys7** [bazaarvoice/magento2-extension#23]
Version 7.0.13
Magento Enterprise 2.2.2 

```
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getSku() on null in /var/www/current/src/vendor/bazaarvoice/bazaarvoice-magento2-ext/Block/Product.php:92
Stack trace:
#0 [internal function]: Bazaarvoice\Connector\Block\Product->getProductSku()
#1 /var/www/current/src/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array)
#2 /var/www/current/src/vendor/bazaarvoice/bazaarvoice-magento2-ext/view/frontend/templates/productheader.phtml(25): Magento\Framework\View\TemplateEngine\Php->__call('getProductSku', Array)
#3 /var/www/current/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/curren...')
#4 /var/www/current/src/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Bazaarvoice\Connector\Block\Reviews), '/var/www/curren...', Array)
#5 /var/www/current/src/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetc
```

**Comment by chrismshea** [comment]
PR Merged into release branch release-716
