### ISSUE TITLE
Magento 2.3.0 - Deprecated Functionality: Function create_function() is deprecated in vendor/bazaarvoice/bazaarvoice-magento2-ext/Helper/Data.php on line 96

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#49]
Magento 2.3.0 throws the following error when running bin/magento index:reindex with the latest version of the plugin.

```
Deprecated Functionality: Function create_function() is deprecated in vendor/bazaarvoice/bazaarvoice-magento2-ext/Helper/Data.php on line 96
#0 vendor/bazaarvoice/bazaarvoice-magento2-ext/Helper/Data.php(96): Magento\Framework\App\ErrorHandler->handler(8192, 'Function create...', '/home/ccarnell/...', 96, Array)
#1 vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(709): Bazaarvoice\Connector\Helper\Data->getProductId('1-4-138849')
#2 vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(230): Bazaarvoice\Connector\Model\Indexer\Flat->reindexProductsForStore(Array, Object(Magento\Store\Model\Store\Interceptor))
#3 vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(183): Bazaarvoice\Connector\Model\Indexer\Flat->reindexProducts(Array)
#4 vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(133): Bazaarvoice\Connector\Model\Indexer\Flat->execute(Array)
#5 vendor/magento/module-indexer/Model/Indexer.php(413): Bazaarvoice\Connector\Model\Indexer\Flat->executeFull()
#6 generated/code/Magento/Indexer/Model/Indexer/Interceptor.php(323): Magento\Indexer\Model\Indexer->reindexAll()
#7 vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer\Interceptor->reindexAll()
#8 vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(87): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#9 vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/magento/framework/Console/Cli.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
Bazaarvoice Product Feed Index index has been rebuilt successfully in 00:00:00
```

**Comment by chrismshea** [comment]
Hi Craig, What version of PHP are you running.  Tested with 7.1.22

**Comment by craigcarnell** [comment]
@chrismshea PHP 7.2.13

**Comment by craigcarnell** [comment]
Also get this error on frontend:

```
[2018-12-12 10:50:38] report.CRITICAL: Deprecated Functionality: Function create_function() is deprecated in vendor/bazaarvoice/bazaarvoice-magento2-ext/Helper/Data.php on line 96 [] []
```

**Comment by chrismshea** [comment]
Release 7.1.14 is out.  Please update to the latest.

**Comment by craigcarnell** [comment]
@chrismshea Fixed, thank you
