### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#51]
Magento 2.3.0
PHP 7.2.13

bin/magento index:reindex
```
Warning: count(): Parameter must be an array or an object that implements Countable in /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php on line 176
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'count(): Parame...', '/home/ccarnell/...', 176, Array)
#1 /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(176): count(NULL)
#2 /home/ccarnell/Sites/vax-uk2/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(132): Bazaarvoice\Connector\Model\Indexer\Flat->execute(Array)
#3 /home/ccarnell/Sites/vax-uk2/vendor/magento/module-indexer/Model/Indexer.php(413): Bazaarvoice\Connector\Model\Indexer\Flat->executeFull()
#4 /home/ccarnell/Sites/vax-uk2/generated/code/Magento/Indexer/Model/Indexer/Interceptor.php(323): Magento\Indexer\Model\Indexer->reindexAll()
#5 /home/ccarnell/Sites/vax-uk2/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(248): Magento\Indexer\Model\Indexer\Interceptor->reindexAll()
#6 /home/ccarnell/Sites/vax-uk2/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(87): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#7 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/ccarnell/Sites/vax-uk2/vendor/magento/framework/Console/Cli.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/ccarnell/Sites/vax-uk2/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/ccarnell/Sites/vax-uk2/bin/magento(23): Symfony\Component\Console\Application->run()
#13 {main}
Bazaarvoice Product Feed Index index has been rebuilt successfully in 00:00:19
```

FYI a work around is to check for is_array first.

**Comment by chrismshea** [comment]
Pushed a new version 7.1.15
