### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in Model/Feed/Product/Generic.php:93

### ISSUE THREAD

**Issue by leek** [bazaarvoice/magento2-extension#53]
This seems to be the same issue described in #30 but is occuring with the latest version of the extension (`7.1.15`).

This happens when trying to run: `bin/magento indexer:reindex`:

```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /html/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Feed/Product/Generic.php:93
Stack trace:
#0 /html/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Indexer/Flat.php(100): Bazaarvoice\Connector\Model\Feed\Product\Generic->getLocales()
#1 /html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Bazaarvoice\Connector\Model\Indexer\Flat->__construct(Object(Bazaarvoice\Connector\Logger\Logger), Object(Bazaarvoice\Connector\Helper\Data), Object(Magento\Indexer\Model\Indexer\DependencyDecorator), Object(Magento\Framework\App\ObjectManager), Object(Magento\Store\Model\StoreManager), Object(Bazaarvoice\Connector\Model\ResourceModel\Index\Collection\Factory), Object(Magento\Framework\App\ResourceConnection\Interceptor), Object(Magento\Framework\App\Config), Object(Baz in /html/vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Feed/Product/Generic.php on line 93
```

**Comment by jantzenw** [comment]
Cleaning up old issue requests. This code has since been refactored and the issue fixed.
